---
- name: Initialize Terraform AWS Provisioner
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Clone Terraform repo to server
      git:
        repo: https://github.com/michaelford85/aws-terraform.git
        dest: /tmp/aws-terraform

    - name: Initialize Terraform
      command:
        cmd: terraform init
        chdir: /tmp/aws-terraform
