---
- name: Prune Groups in AWS Terraform Inventory
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/default-vars.yml
    - ../credentials/tower_creds.yml

  tasks:


    - name: Remove us-east-1 group
      tower_group:
        inventory: AWS Terraform Inventory
        name: us-east-1
        state: absent
        tower_host: "{{ tower_url }}"
        tower_username: "{{ tower_user }}"
        tower_password: "{{ tower_pass }}"
        tower_verify_ssl: false
      delegate_to: localhost

    - name: Remove regions group
      tower_group:
        inventory: AWS Terraform Inventory
        name: regions
        state: absent
        tower_host: "{{ tower_url }}"
        tower_username: "{{ tower_user }}"
        tower_password: "{{ tower_pass }}"
        tower_verify_ssl: false
      delegate_to: localhost
