---
- name: Provision AWS infrastructure via Terraform
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Provision AWS Instances/Resources via Terraform
      terraform:
        project_path: /tmp/aws-terraform
        state: present
      register: terraform_output

    - name: Debug Terraform output
      debug:
        var: terraform_output
      tags:
        - debug
